# Generated by Django 2.2 on 2020-06-21 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twisteduser',
            options={'verbose_name': 'users'},
        ),
    ]
