# Generated by Django 2.2 on 2020-06-21 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200621_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twisteduser',
            options={'verbose_name': 'users', 'verbose_name_plural': 'users'},
        ),
    ]
