# Generated by Django 2.2 on 2020-06-21 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200621_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twisteduser',
            options={'verbose_name': 'users'},
        ),
    ]
